# Generated by Django 6.0.6 on 2026-07-03 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_text', models.TextField()),
                ('learning_hours', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['class_level'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.TextField(help_text='Base64 string or image URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['sector_name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.TextField()),
            ],
            options={
                'ordering': ['lname', 'fname'],
            },
        ),
        migrations.CreateModel(
            name='IndicativeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indic_name', models.TextField()),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicative_contents', to='core.learningoutcome')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_code', models.CharField(max_length=50, unique=True)),
                ('mod_name', models.CharField(max_length=150)),
                ('learning_hours', models.IntegerField()),
                ('term', models.CharField(max_length=50)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.level')),
            ],
            options={
                'ordering': ['mod_code'],
            },
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='core.module'),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=150)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.sector')),
            ],
            options={
                'ordering': ['trade_name'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.trade'),
        ),
        migrations.AddField(
            model_name='module',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='core.trainer'),
        ),
        migrations.CreateModel(
            name='TradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_levels', to='core.level')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_levels', to='core.trade')),
            ],
            options={
                'ordering': ['trade__trade_name', 'level__class_level'],
                'unique_together': {('trade', 'level')},
            },
        ),
    ]
