# Generated by Django 6.0.4 on 2026-07-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
