# Generated by Django 5.1.15 on 2026-07-03 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('week', models.CharField(blank=True, max_length=50)),
                ('lesson_date', models.DateField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='core.module')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='core.trainer')),
            ],
            options={
                'ordering': ['-lesson_date', 'title'],
            },
        ),
    ]
