# Generated by Django 6.1 on 2026-08-22 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assessmentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_generation_used', models.BooleanField(default=False, help_text='Whether this trainer has already used their 1 free generation (shared across Scheme of Work, Lesson Plan and Assessment Plan).')),
                ('is_paid', models.BooleanField(default=False, help_text='Admin toggles this on after confirming an offline MTN MoMo payment. Turning it on sets a 90-day access window automatically.')),
                ('paid_until', models.DateField(blank=True, help_text='Access expires at the end of this date. Set automatically to 90 days from when an Admin marks this trainer Paid.', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Optional MoMo transaction reference / note for this payment.', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='core.trainer')),
            ],
        ),
    ]
